
* Do you know what a "logic bug" is ? 

It's a term that some folk use to mean a bug not when you didn't
understand the API, or when you didn't think through concurrency
issues. But just when the plain, ordinary expressions in your program
don't make logical sense in the way you thought they did.

It *also* means something that cost Intel half a billion dollars in
1994 money. Back then a dollar meant something. 

* My name is Jason Hemann 

** I *love* ACL2

** I *love* proving theorems

** I *love* formal methods proving correctness of models. 

* Raise your hand if you got stopped or stuck by small bugs in your Racket programs

** Raise your hand if you wanted to see your purpose statements *checked* for you, rather than just written. 

* Small bugs.

* This would be a great time to transform the Ackermann program. (equational reasoning)

This would be a great introductory example of a program, and to
remember such programs. 

This would be a great programming reminder/review, and it would let me
illustrate what we can do with programming. 

** Holy moly I could do an interpreter
